/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;
import java.util.HashSet;
import java.util.LinkedList;

public class App {
    public static void main(String[] args) {

        Graph graph = new Graph();
        Node shamikh = graph.addNode("shamikh");
        Node ahmad = graph.addNode("ahmad");
        Node aya = graph.addNode("aya");
        Node walaa = graph.addNode("walaa");
        System.out.println("Graph: "+graph.getNodes());
        System.out.println("Size of graph is :"+graph.getSize());
        System.out.println(graph.addEdge(shamikh, ahmad));

        HashSet<Node> expected = new HashSet<>();
        expected.add(shamikh);
        expected.add(ahmad);
        expected.add(aya);
        System.out.println("Graph: "+graph.getNodes());


        Graph graph2 = new Graph();
        Node one = graph.addNode("one");
        Node tow = graph.addNode("tow");
        Node three = graph.addNode("three");
        one.addNeighbor(tow);
        one.addNeighbor(three);
        for (Object neighbor : one.neighbors) {
            System.out.println("neighbor of one: " + one.neighbors);
        }

            Graph newGraph = new Graph();
            Node firstOne = newGraph.addNode("shamikh");
            Node secondOne = newGraph.addNode("ahmad");
            Node thirdOne = newGraph.addNode("aya");
            shamikh.addNeighbor(ahmad, 60);
            shamikh.addNeighbor(aya, 55);
            LinkedList<Node> newList = new LinkedList<>();
            newList.add(shamikh);
            newList.add(ahmad);
            newList.add(aya);
        System.out.println("new Graph after applied breadthFirst: " +  newGraph.breadthFirstSearch(shamikh));
        System.out.println("newList after inserting elements : " +  newGraph.breadthFirstSearch(shamikh));


    }

}
