/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void mergeSort(){
        MergeSort mergeSort = new MergeSort();
        int arr[] = {8,4,23,42,16,15};
        mergeSort.mergeSort(arr);
        String res = Arrays.toString(arr);
        assertEquals("[4, 8, 15, 16, 23, 42]" , res);
    }


}
