/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

public class AppTest {
    @Test
    public void testInsertSortArr() {
        int[] Arr = {20,33,12,8,46,-8};
        int[] outputArray = InsertionSort.insertSort(Arr);
        int[] expectedOutput={-8,8,12,20,33,46};
        assertArrayEquals(expectedOutput,outputArray);
    }
}
