/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;
import java.util.Arrays;
public class App {
    public static void main(String[] args) {
        QuickSort quickSort = new QuickSort();
        int[] array1 = {8,4,23,42,16,15};
        int[] array2 = {20,18,12,8,5,-2};
        int[] array3 = {16,2,1,30,28,4,-19};


        int[] arraySorted1 = quickSort.sortArr(array1);
        int[] arraySorted2 = quickSort.sortArr(array2);
        int[] arraySorted3 = quickSort.sortArr(array3);


        System.out.println("Array1 after Sorting: "+Arrays.toString(arraySorted1));
        System.out.println("Array2 after Sorting: "+Arrays.toString(arraySorted2));
        System.out.println("Array3 after Sorting: "+Arrays.toString(arraySorted3));


    }
}