/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;
import org.junit.jupiter.api.Test;
import java.util.Arrays;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void quickSortTest(){
        int arr[] = {8,4,23,42,16,15};
        QuickSort quickSort=new QuickSort();
        quickSort.sortArr(arr);
        String res= Arrays.toString(arr);
        assertEquals("[4, 8, 15, 16, 23, 42]",res);
    }
}
