/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hash.Table;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        HashTable<String,Integer> hashTable= new HashTable<>();
        hashTable.add("Shamikh" , 811);
        Integer key = hashTable.get("Shamikh");
        System.out.println(key);
        hashTable.add("10", 36);
        System.out.println( hashTable.contains("10"));
    }

}
