/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testEmptyTree(){
        BinaryTree emptyTree=new BinaryTree();
        assertEquals(null,emptyTree.root);
    }
    @Test
    void testOneRootNode(){
        BinarySearchTree singleNode=new BinarySearchTree();
        singleNode.insert(22);
        ArrayList expectedVlue=new ArrayList();
        expectedVlue.add(22);
        assertEquals(expectedVlue,singleNode.inOrder(singleNode.root));
    }
    @Test
    void testLAndRChild(){
        BinarySearchTree singleNode=new BinarySearchTree();
        singleNode.insert(9);
        singleNode.insert(5);
        singleNode.insert(8);
        ArrayList expectedVlue=new ArrayList();
        expectedVlue.add(5);
        expectedVlue.add(8);
        expectedVlue.add(9);
        assertEquals(expectedVlue,singleNode.inOrder(singleNode.root));
    }
    @Test
    void testPreOrder(){
        BinarySearchTree singleNode=new BinarySearchTree();
        singleNode.insert(6);
        singleNode.insert(4);
        singleNode.insert(5);
        ArrayList expectedVlue=new ArrayList();
        expectedVlue.add(6);
        expectedVlue.add(4);
        expectedVlue.add(5);
        assertEquals(expectedVlue,singleNode.preOrder(singleNode.root));
    }
    @Test
    void testInorder(){
        BinarySearchTree singleNode=new BinarySearchTree();
        singleNode.insert(22);
        singleNode.insert(30);
        singleNode.insert(40);
        ArrayList expectedVlue=new ArrayList();
        expectedVlue.add(22);
        expectedVlue.add(30);
        expectedVlue.add(40);
        assertEquals(expectedVlue,singleNode.inOrder(singleNode.root));
    }

}